### ISSUE TITLE
Abort: Assertion `dec->image->cmprof_' failed (jp2_dec.c)

### ISSUE THREAD

**Issue by jridky** [jasper-software/jasper#139] opened 2017-05-23 14:01 UTC
Quick reproducer using jasper:
```
$ curl -sO http://www.fnordware.com/j2k/relax.jp2
$ jasper --input relax.jp2 --output /dev/null --output-format jpg
ICC Profile CS 52474220
jasper: jp2_dec.c:308: jp2_decode: Assertion `dec->image->cmprof_' failed.
Aborted (core dumped)
```

debug output: [here](https://pastebin.com/iZGQTuJf)

**Comment by nullne** [comment] 2017-08-01 01:58
same problem, who can provide any solutions?

**Comment by D4N** [comment] 2018-01-05 22:47
In case it provides any further insight, a file that caused a bug in exiv2 causes the same assertion with jasper and makes pcmanfm crash when I open my exiv2 folder with the images for regression tests.

The issue is can be found [here](https://github.com/Exiv2/exiv2/issues/188). The problem in that case was an arithmetic overflow, as it can be found in the discussion of the bug report. Hope this helps a bit.

**Comment by jubalh** [comment] 2020-07-28 14:46
Fixed with our merges from jasper-maint:

```
jasper --input ~/jasper/relax.jp2 --output /dev/null --output-format jpg
ICC Profile CS 52474220
error: cannot load image data
```

Not entirely sure which commit, and don't think git bisecting it is worth it here.
2.0.19 is thus fixed.

**Closed by jubalh** 2020-07-28 14:46 UTC
