### ISSUE TITLE
Use of --gc-sections

### ISSUE THREAD

**Issue by haampie** [jasper-software/jasper#322] opened 2022-05-11 11:41 UTC
Commit 0f020fd73bb8fa74a1a5557c4280ff5722d94d62 changed the default of jasper to use the `--gc-sections` linker flag.

The project here: https://confluence.ecmwf.int/display/ECC depends on those symbols (for example `jpc_encode`) that are pruned by the linker.

Wouldn't it be better to leave the default to `JAS_ENABLE_HIDDEN=OFF`?

**Comment by mdadams** [comment] 2022-05-11 22:56
The decision to make hiding symbols the default behavior is deliberate.   Library users shouldn't rely on the symbols that are would be hidden by this option, as such symbols are not part of the official library API and could change or be deleted without warning.  What symbols are you relying on that are hidden by default (just to be sure that something that is part of the API was not accidentally marked as hidden)?

**Comment by mdadams** [comment] 2022-06-19 04:31
Since I have not received any response in over a month, I am going to assume that the problem is not due to a JasPer library API symbol being accidentally marked as hidden when it should not be (i.e., the problem is not due to a bug in JasPer but rather due to the library user making use of symbols that are not part of the JasPer library API).  Since this is not a bug, I am going to close this issue.

**Closed by mdadams** 2022-06-19 04:31 UTC
