### ISSUE TITLE
Out of bound read in dec_clnpass

### ISSUE THREAD

**Issue by adarshdinesh** [jasper-software/jasper#124] opened 2017-03-25 13:31 UTC
gdb-peda$ r out_of_bound_read_dec_clnpass
Starting program: /home/sandbox/Desktop/fuzz/bin out_of_bound_read_dec_clnpass
warning: trailing garbage in marker segment (40 bytes)
warning: ignoring trailing garbage (57 bytes)
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad termination pattern detected
warning: bad segmentation symbol
warning: bad termination pattern detected
warning: bad segmentation symbol

Program received signal SIGSEGV, Segmentation fault.

 [----------------------------------registers-----------------------------------]
RAX: 0xfffffffffe800030 
RBX: 0x60e4d0 --> 0x7e00000 
RCX: 0xfffffffffe800000 
RDX: 0x9002 
RSI: 0x60e4d0 --> 0x7e00000 
RDI: 0x60e4d0 --> 0x7e00000 
RBP: 0x7fffffffdb90 --> 0x7fffffffdc10 --> 0x7fffffffdc80 --> 0x7fffffffdd00 --> 0x7fffffffdd40 --> 0x7fffffffdd80 (--> ...)
RSP: 0x7fffffffdac0 --> 0x0 
RIP: 0x7ffff7ba5693 (<dec_clnpass+1204>:	mov    rax,QWORD PTR [rax])
R8 : 0x1 
R9 : 0x1 
R10: 0x1 
R11: 0x246 
R12: 0x7ffff7f9b840 --> 0x110 
R13: 0x7ffff7f1b820 --> 0x0 
R14: 0x0 
R15: 0x0
EFLAGS: 0x10286 (carry PARITY adjust zero SIGN trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x7ffff7ba5687 <dec_clnpass+1192>:	mov    QWORD PTR [rbx+0x18],rax
   0x7ffff7ba568b <dec_clnpass+1196>:	mov    rdx,QWORD PTR [rbx+0x8]
   0x7ffff7ba568f <dec_clnpass+1200>:	mov    rax,QWORD PTR [rbx+0x18]
=> 0x7ffff7ba5693 <dec_clnpass+1204>:	mov    rax,QWORD PTR [rax]
   0x7ffff7ba5696 <dec_clnpass+1207>:	mov    rax,QWORD PTR [rax]
   0x7ffff7ba5699 <dec_clnpass+1210>:	sub    rdx,rax
   0x7ffff7ba569c <dec_clnpass+1213>:	mov    rax,rdx
   0x7ffff7ba569f <dec_clnpass+1216>:	mov    QWORD PTR [rbx+0x8],rax
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffdac0 --> 0x0 
0008| 0x7fffffffdac8 --> 0x100000001 
0016| 0x7fffffffdad0 --> 0x1800000000 
0024| 0x7fffffffdad8 --> 0x0 
0032| 0x7fffffffdae0 --> 0x7fffffffdf40 --> 0x2 
0040| 0x7fffffffdae8 --> 0x0 
0048| 0x7fffffffdaf0 --> 0x1000078fe 
0056| 0x7fffffffdaf8 --> 0x100000000000880 
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
0x00007ffff7ba5693 in dec_clnpass () from /usr/lib/libjasper.so.4

gdb-peda$ backtrace 
#0  0x00007ffff7ba5693 in dec_clnpass () from /usr/lib/libjasper.so.4
#1  0x00007ffff7ba2272 in jpc_dec_decodecblk () from /usr/lib/libjasper.so.4
#2  0x00007ffff7ba1b86 in jpc_dec_decodecblks () from /usr/lib/libjasper.so.4
#3  0x00007ffff7b8b5d2 in jpc_dec_tiledecode () from /usr/lib/libjasper.so.4
#4  0x00007ffff7b89cb4 in jpc_dec_process_sod () from /usr/lib/libjasper.so.4
#5  0x00007ffff7b89425 in jpc_dec_decode () from /usr/lib/libjasper.so.4
#6  0x00007ffff7b89005 in jpc_decode () from /usr/lib/libjasper.so.4
#7  0x00007ffff7b731cd in jas_image_decode () from /usr/lib/libjasper.so.4
#8  0x0000000000400f4f in main ()
#9  0x00007ffff74ac830 in __libc_start_main (main=0x400e76 <main>, argc=0x2, argv=0x7fffffffdf48, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdf38) at ../csu/libc-start.c:291
#10 0x0000000000400da9 in _start ()
gdb-peda$ x/x 0xfffffffffe800030
0xfffffffffe800030:	Cannot access memory at address 0xfffffffffe800030
gdb-peda$ 

[out_of_bound_read_dec_clnpass.zip](https://github.com/mdadams/jasper/files/870046/out_of_bound_read_dec_clnpass.zip)

**Comment by asarubbo** [comment] 2017-03-30 13:49
The stacktrace looks to be the same of the already reported #90 

So it can have the same root cause.

**Comment by jubalh** [comment] 2020-07-28 14:41
Fixed with our merges from jasper-maint:

```
imginfo -f ~/jasper/out_of_bound_read_dec_clnpass
image too large
cannot load image

```

Not entirely sure which commit, and don't think git bisecting it is worth it here.
2.0.19 is thus fixed.

**Closed by jubalh** 2020-07-28 14:41 UTC
